name: thesis
dependencies:
- appnope=0.1.0=py35_0
- cloudpickle=0.1.1=py35_0
- cymem=1.30=py35_0
- cython=0.23.4=py35_1
- decorator=4.0.9=py35_0
- ipykernel=4.2.2=py35_0
- ipython=4.1.1=py35_0
- ipython_genutils=0.1.0=py35_0
- jinja2=2.8=py35_0
- jsonschema=2.4.0=py35_0
- jupyter_client=4.1.1=py35_0
- jupyter_core=4.0.6=py35_0
- markupsafe=0.23=py35_0
- mistune=0.7.1=py35_0
- mkl=11.3.1=0
- murmurhash=0.26.0=py35_0
- nbconvert=4.1.0=py35_0
- nbformat=4.0.1=py35_0
- notebook=4.1.0=py35_0
- numpy=1.10.4=py35_0
- openssl=1.0.2f=0
- pandas=0.17.1=np110py35_0
- path.py=8.1.2=py35_1
- pexpect=3.3=py35_0
- pickleshare=0.5=py35_0
- pip=8.0.3=py35_0
- plac=0.9.1=py35_0
- preshed=0.46.1=py35_0
- ptyprocess=0.5=py35_0
- pygments=2.1.1=py35_0
- python=3.5.1=0
- python-dateutil=2.4.2=py35_0
- python.app=1.2=py35_4
- pytz=2015.7=py35_0
- pyzmq=15.2.0=py35_0
- readline=6.2=2
- requests=2.9.1=py35_0
- scipy=0.17.0=np110py35_0
- semver=2.3.1=py35_0
- setuptools=20.1.1=py35_0
- simplegeneric=0.8.1=py35_0
- six=1.10.0=py35_0
- sputnik=0.8.2=py35_0
- sqlite=3.9.2=0
- terminado=0.5=py35_1
- text-unidecode=1.0=py35_0
- thinc=5.0.4=py35_0
- tk=8.5.18=0
- tornado=4.3=py35_0
- traitlets=4.1.0=py35_0
- ujson=1.35=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-core==4.0.6
  - protobuf==3.0.0a3
  - tensorflow==0.7.0

