python main.py configs/svm.yaml
python main.py configs/svm_1.yaml
python main.py configs/svm_2.yaml
python main.py configs/svm_3.yaml
python main.py configs/svm_4.yaml
python main.py configs/svm_5.yaml
python main.py configs/svm_6.yaml
python main.py configs/svm_7.yaml
python main.py configs/svm_8.yaml
python main.py configs/svm_9.yaml
python main.py configs/svm_10.yaml
