model:
    name: mlp
    epochs: 100
    batch_size: 1000
    store_path: models/mlp.ckpt

test_report_path: results/mlp.txt


# Each extractor has a name from main.extractor_handlers, which points to a class
# where any additional params are used to initiate the extractor class.

extractors:
    # -
    #     name: word2vec
    #     path: resources/GoogleNews-vectors-negative300.bin
    # -
    #     name: onehot
    #     vocab_indices_path: resources/conll16st-en-zh-dev-train_LDC2016E50/vocab.txt
    -
        name: random_cbow
        dimensionality: 300
        argument: arg1_text
    -
        name: random_cbow
        dimensionality: 300
        argument: arg2_text
    -
        name: random_cbow
        dimensionality: 300
        argument: connective_token
