# train: false

model:
    name: svm
    kernel: rbf
    store_path: models/svm_nonlinear.ckpt

test_output_path: results/svm_nonlinear.json

experiment_name: "SVM baseline"
description: "An SVM baseline using random cbow with arg1 and arg2"
tags: ['svm', 'baseline', 'non_linear', 'random_cbow', 'arg2_text', 'arg1_text']

# Each extractor has a name from main.extractor_handlers, which points to a class
# where any additional params are used to initiate the extractor class.

extractors:
     -
         name: random_cbow
         dimensionality: 300
         argument: arg1_text
     -
         name: random_cbow
         dimensionality: 300
         argument: arg2_text
